Haiderali29/explore events screen
nooralibutt/playon pull request #14
Opened 2021-09-22 12:48 UTC by Haiderali29

closes #
![Screenshot_2021-09-22-17-45-29-585_com nab playon](https://user-images.githubusercontent.com/89379073/134346138-09391f82-3e7b-4687-9bbf-40c6cd51d0de.jpg)
6

2021-09-23 06:39 UTC, ahmadkhandev requested changes

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_card.dart
> +          width: kEventCardOuterWidth,
taking width & height in parameters isn't a better option?

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_card.dart
> +                          color: kEventCardShadowColor,
instead of redefining new constants, try using the ones defined in AppTheme for colors. It will also be reflecting which colour we are using.

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_card.dart
> +                          padding: const EdgeInsets.only(left: 15.0, top: 15.0),
could have applied padding over the Column and used VerticalSpacing() for spacing between items.

edit the below ones too.

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_card.dart
> +                  margin: EdgeInsets.fromLTRB(0, 103, 0, 0))
instead use EdgeInsets.only

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_card.dart
> +                      color: Color(0xffF7F7F7),
try using AppTheme colors. if you couldn't find the one you need, define one.

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +                height: 15.8,
instead of using the exact values from Zeplin, use near rounded figure. for example, in this case it should be 15.0

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +                child: TextFormField(
Search of TextField which has leading and trailing icon and use that instead

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +                child: Image(image: AssetImage('assets/images/search.png')),
use Icons instead of images

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +class ExploreEvents extends StatefulWidget {
always add Screen suffix to the class name of a screen

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +                    ''.toText()
instead use EmptyWidget which is SizedBox with 0 lengths.

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/utils/constants.dart
> +const kEventCardOuterWidth = 318.0;
you don't need to define all lengths here

2021-09-23 06:39 UTC, ahmadkhandev commented on lib/utils/constants.dart
> +const kEventCardHeaderValueColor = Color(0xff11263c);
use colors from AppTheme instead. remove all from constants

2021-09-24 12:19 UTC, nooralibutt requested changes

2021-09-24 12:19 UTC, nooralibutt commented on lib/screens/explore_events/explore_events_screen.dart
> +    _tabController = new TabController(length: 2, vsync: this);
remove new keyword

2021-09-28 06:31 UTC, ahmadkhandev requested changes

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/components/bottom_appbar_icon.dart
> +      icon: Icon(icon, color: AppTheme.lightBlueGreyColor),
how will you be changing the cooler if that Icon is selected?

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/components/event_details_body.dart
> +      : super(key: key);
write constructor below the data members

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +    this.obscure = false,
you don't need obscure & keyboard type here

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +              child: Icon(FontAwesomeIcons.slidersH, color: AppTheme.primary)),
add onTap for this icon. get it as a parameter

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +  static const String routName = '/ExploreEventScreen';
try to write it at the top of class, then data members and then constructor.

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +                    fontStyle: FontStyle.normal,
do we need to mention normal? isn't it normal by default?

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +                      )),
do we really need SizedBox here? Icon widget has a size property. plus we can use const with it

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +  const SearchBar({
add TextController for it

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +                                imagePath: EventCardDetails
could have stored the list in a local variable instead of accessing the class every time

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/screens/explore_events/explore_events_screen.dart
> +                      HorizontalSpacing(of: 70),
must have used const

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/utils/app_theme.dart
> +  static const Color lightSilver = Color(0xFFF5F6F8);
when adding a new thing, always see how the neighbouring elements are written. rename this.

2021-09-28 06:31 UTC, ahmadkhandev commented on lib/utils/constants.dart
> +const kEventCardHeaderValueStyle = TextStyle(
reconfirm if these will be used at more than one places, then keep it here. Otherwise, use properties directly in toText().

2021-09-28 11:24 UTC, Haiderali29 commented on lib/utils/constants.dart
> +const kEventCardHeaderValueStyle = TextStyle(
it is used more than once

2021-09-29 08:45 UTC, nooralibutt commented on lib/utils/routes.dart
>    SignupScreen.routeName: (context) => SignupScreen(),
mark it const as well

2021-09-29 11:59 UTC, nooralibutt requested changes

2021-09-29 11:59 UTC, nooralibutt commented on lib/screens/explore_events/components/event_card.dart
> +              EventCardImage(data: data),
pass only image here

2021-09-29 11:59 UTC, nooralibutt commented on lib/screens/explore_events/components/event_card.dart
> +                      EventCardHeader(data: data),
pass only relevant data here

2021-09-29 15:16 UTC, ahmadkhandev requested changes

2021-09-29 15:16 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +  final bool enabled;
why would we need it in the SearchBar? it shouldn't always be enabled?

2021-09-29 15:16 UTC, ahmadkhandev commented on lib/screens/explore_events/components/search_bar.dart
> +  static void _onTapSearchIcon(BuildContext context) {
we don't need it here. search is just an icon without any tap functionality.

2021-09-30 05:07 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_card.dart
> +              EventCardImage(data: data),
Done

2021-09-30 05:07 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_card.dart
> +                      EventCardHeader(data: data),
Done

2021-09-30 05:07 UTC, Haiderali29 commented on lib/screens/explore_events/components/EventCardHeader.dart
> +  final EventCardDetails data;
Done

2021-09-30 05:07 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_card_image.dart
> +  final EventCardDetails data;
Done

2021-09-30 05:13 UTC, Haiderali29 commented on lib/screens/explore_events/components/explore_events_body.dart
> +          kEmptyWidget
No it shows error

2021-09-30 05:14 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_details_body.dart
> +      ),
these paddings are not symmetric thats why we have to use padding

2021-09-30 05:19 UTC, Haiderali29 commented on lib/screens/explore_events/components/search_bar.dart
> +  static void _onTapSearchIcon(BuildContext context) {
Done

2021-09-30 05:19 UTC, Haiderali29 commented on lib/screens/explore_events/components/search_bar.dart
> +  final bool enabled;
Done

2021-09-30 05:19 UTC, Haiderali29 commented on lib/screens/explore_events/components/notched_bottom_navigation_bar.dart
> +        shape: CircularNotchedRectangle(),
Done

2021-09-30 06:14 UTC, mhanzla80 requested changes

2021-09-30 06:14 UTC, mhanzla80 commented on lib/screens/explore_events/components/search_bar.dart
> +  final TextEditingController controller = TextEditingController();
this should be private

2021-09-30 06:14 UTC, mhanzla80 commented on lib/screens/explore_events/components/event_details_body.dart
> +      decoration: BoxDecoration(
make saperate variable for decoration.

2021-09-30 06:14 UTC, mhanzla80 commented on lib/screens/explore_events/components/explore_events_body.dart
> +        ], controller: _tabController))
place this at the top

2021-09-30 06:14 UTC, mhanzla80 commented on lib/screens/explore_events/explore_events_screen.dart
> +            body: ExploreEventsBody(),
this should be const.

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_card.dart
> +                margin: EdgeInsets.only(top: 40.0),
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_details_body.dart
> +      margin: EdgeInsets.only(top: 5),
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/explore_events_body.dart
> +                insets: EdgeInsets.symmetric(horizontal: 75.0)),
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/search_bar.dart
> +  final TextEditingController controller = TextEditingController();
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/event_details_body.dart
> +      decoration: BoxDecoration(
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/components/explore_events_body.dart
> +        ], controller: _tabController))
done

2021-09-30 06:25 UTC, Haiderali29 commented on lib/screens/explore_events/explore_events_screen.dart
> +            body: ExploreEventsBody(),
done

2021-09-30 06:45 UTC, mhanzla80 approved these changes

2021-09-30 07:30 UTC, nooralibutt approved these changes

2021-09-30 07:32 UTC, merged