Haiderali29/signup screen UI #3
nooralibutt/playon pull request #15
Opened 2021-09-24 06:24 UTC by Haiderali29

Closes #3 
<img src="https://user-images.githubusercontent.com/89379073/134627754-a6ff3293-e5e8-4453-a4a3-f9ecce0a28fe.jpg" width="200" />
<img src="https://user-images.githubusercontent.com/89379073/134627756-7d632a16-f904-4168-a5fd-9431c50a819c.jpg" width=''200" />

2021-09-24 06:45 UTC, ahmadkhandev commented on lib/screens/signup/components/signup_method_button.dart
> +class SignUpMethodButton extends StatelessWidget {
rename it to SocialSignupButton

2021-09-24 06:53 UTC, ahmadkhandev requested changes

2021-09-24 06:53 UTC, ahmadkhandev commented on lib/screens/signup/signup_screen.dart
> +  static const signupUi = '/SignupScreen';
always use routeName

2021-09-24 06:53 UTC, ahmadkhandev commented on lib/screens/signup/signup_screen.dart
> +  final TextEditingController _controllerUsername = TextEditingController();
use Name instead of Username

2021-09-24 06:53 UTC, ahmadkhandev commented on lib/screens/signup/signup_screen.dart
> +                      width: double.maxFinite,
double.infinity

2021-09-24 06:54 UTC, ahmadkhandev commented on lib/screens/signup/signup_screen.dart
> +                  OnBoardingTextField(
selectedColor should be primary. Look into that

2021-09-24 07:11 UTC, ahmadkhandev submitted a review, later dismissed

2021-09-24 18:07 UTC, nooralibutt requested changes

2021-09-28 06:09 UTC, ahmadkhandev commented on lib/screens/signup/components/caption_text_field.dart
> +      required this.obscure});
make it not required & false as default

2021-09-28 06:10 UTC, ahmadkhandev commented on lib/screens/signup/components/social_signup_button.dart
> +      : super(key: key);
write constructor below and the data members above

2021-09-28 07:09 UTC, ahmadkhandev approved these changes

2021-09-28 07:23 UTC, nooralibutt requested changes

2021-09-28 07:23 UTC, nooralibutt commented on lib/screens/signup/signup_screen.dart
> +class _SignupScreenState extends State<SignupScreen> {
Refactor whole screen

2021-09-28 08:08 UTC, ahmadkhandev commented on lib/screens/signup/components/corner_button.dart
> +class CornerButton extends StatelessWidget {
rename it AlignedTextButton and take alignment as a parameter

2021-09-28 10:00 UTC, ahmadkhandev submitted a review, later dismissed

2021-09-28 11:37 UTC, ahmadkhandev commented
@Haiderali29 use this callback:

`typedef BuildContextCallback = void Function(BuildContext context);`

2021-09-28 11:37 UTC, nooralibutt requested changes

2021-09-29 05:52 UTC, ahmadkhandev approved these changes

2021-09-29 06:18 UTC, nooralibutt submitted a review, later dismissed

2021-09-29 06:18 UTC, nooralibutt commented on lib/screens/signup/components/signup_form.dart
> +        TextEditingController();
these should be outside build method

2021-09-29 07:32 UTC, nooralibutt approved these changes

2021-09-29 07:33 UTC, merged