Tayyab 98/game kind
nooralibutt/playon pull request #21
Opened 2021-09-24 13:11 UTC by Tayyab-98

2021-09-24 18:07 UTC, nooralibutt requested changes
images for rugby and tennis are not quite accurate. We need to get them from Khilji or Hanzla with exact dimensions of the rest of the images.

Also attach images

2021-09-24 18:07 UTC, nooralibutt commented on lib/all_utils.dart
> +export 'package:playon/utils/constants.dart';
why are you exporting already exported files here?

2021-09-24 18:07 UTC, nooralibutt commented on lib/all_screens.dart
> +export 'package:playon/screens/game_kind/constants/constants.dart';
we do not export everything in all screens file, only screens

2021-09-25 10:44 UTC, Tayyab-98 commented on lib/all_utils.dart
> +export 'package:playon/utils/constants.dart';
oh my mistake 
i will resolve this asap

2021-09-26 17:55 UTC, ahmadkhandev commented on lib/screens/game_kind/components/game_card.dart
> +                  style: kGameCardStyle,
if we are using this style only in GameCard, try to write it here explicitly.

2021-09-26 17:56 UTC, ahmadkhandev commented on lib/screens/game_kind/components/game_card.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 48.w),
we don't need to add .w with padding. test if it works well for you without it.

2021-09-26 18:00 UTC, ahmadkhandev requested changes

2021-09-26 18:00 UTC, ahmadkhandev commented on lib/screens/game_kind/game_kind_screen.dart
> +              GameCard(
can't we use const here as well?

2021-09-27 06:51 UTC, Tayyab-98 commented on lib/all_utils.dart
> +export 'package:playon/utils/constants.dart';
done

2021-09-27 06:51 UTC, Tayyab-98 commented on lib/all_screens.dart
> +export 'package:playon/screens/game_kind/constants/constants.dart';
done

2021-09-27 06:56 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 48.w),
halka sa difference ata ha

2021-09-27 06:57 UTC, Tayyab-98 commented on lib/screens/game_kind/components/my_app_bar.dart
> +              child: 'Skip'.toText(
done

2021-09-27 06:58 UTC, Tayyab-98 commented on lib/screens/game_kind/components/my_app_bar.dart
> +                  fontSize: 15.sp,
done

2021-09-27 07:01 UTC, Tayyab-98 commented on lib/screens/game_kind/constants/constants.dart
> +const String kGameKindScreenHeader = 'What kind of game do you prefer?';
done

2021-09-27 07:02 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +          TimelineIndicator(
done

2021-09-28 06:59 UTC, ahmadkhandev commented on lib/screens/game_kind/components/game_card.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 48.w),
no need to add .w. remove it

2021-09-28 07:55 UTC, mhanzla80 requested changes

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +              side: BorderSide(color: color, width: 1.5),
this should be const.

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +                  child: Image(image: AssetImage(widget.image)),
const it.

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +                      side: BorderSide(color: AppTheme.whiteColor),
const plz

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +                      shape: CircleBorder(),
const

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +                  style: TextStyle(fontSize: 17, color: Color(0xff11263c)),
const

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/my_app_bar.dart
> +              child: Text(
change it to toText.

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/components/my_app_bar.dart
> +                style: TextStyle(
const

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +              padding: EdgeInsets.only(top: 15, left: 33, right: 34),
const.

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +              child: Text('What kind of game do you prefer?',
toText ???

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +          VerticalSpacing(of: 40),
const. ?????

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +              GameCard(
all these could be const.

2021-09-28 07:55 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +          VerticalSpacing(of: 100),
const

2021-09-28 08:02 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +              side: BorderSide(color: color, width: 1.5),
done

2021-09-28 08:02 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                  child: Image(image: AssetImage(widget.image)),
done

2021-09-28 08:03 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                      side: BorderSide(color: AppTheme.whiteColor),
done

2021-09-28 08:03 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                      shape: CircleBorder(),
done

2021-09-28 08:03 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                      shape: CircleBorder(),
done

2021-09-28 08:03 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                  style: TextStyle(fontSize: 17, color: Color(0xff11263c)),
done

2021-09-28 08:03 UTC, Tayyab-98 commented on lib/screens/game_kind/components/my_app_bar.dart
> +              child: Text(
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/my_app_bar.dart
> +              child: Text(
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/my_app_bar.dart
> +                style: TextStyle(
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +              padding: EdgeInsets.only(top: 15, left: 33, right: 34),
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +              child: Text('What kind of game do you prefer?',
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +          VerticalSpacing(of: 40),
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +              GameCard(
done

2021-09-28 08:06 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +          VerticalSpacing(of: 100),
done

2021-09-28 09:05 UTC, mhanzla80 requested changes

2021-09-28 09:05 UTC, mhanzla80 commented on lib/screens/game_kind/components/my_app_bar.dart
> +                style: const TextStyle(
instead of using textStyle use attributes of toText widget.

2021-09-28 09:05 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +                  textAlign: TextAlign.center, style: TextStyle(fontSize: 32))),
remove style assign font to toText.

2021-09-28 09:10 UTC, mhanzla80 submitted a review, later dismissed

2021-09-28 10:57 UTC, Tayyab-98 commented
<img src="https://user-images.githubusercontent.com/89379559/135074370-153e857e-836d-4918-8731-fc2462123c64.png" width="200"/>

2021-09-28 11:33 UTC, mhanzla80 requested changes

2021-09-28 11:33 UTC, mhanzla80 commented on lib/screens/game_kind/components/game_card.dart
> +                      const TextStyle(fontSize: 17, color: Color(0xff11263c)),
remove text style and assign properties to toText widget.

2021-09-28 11:43 UTC, nooralibutt requested changes

2021-09-28 11:43 UTC, nooralibutt commented on lib/screens/game_kind/components/game_card.dart
> +class GameCard extends StatefulWidget {
selection card

2021-09-29 05:10 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +                      const TextStyle(fontSize: 17, color: Color(0xff11263c)),
done

2021-09-29 05:10 UTC, Tayyab-98 commented on lib/screens/game_kind/components/game_card.dart
> +class GameCard extends StatefulWidget {
done

2021-09-29 05:20 UTC, ahmadkhandev requested changes

2021-09-29 05:20 UTC, ahmadkhandev commented on lib/screens/game_kind/components/selection_card.dart
> +  final String image;
rename it to imagePath

2021-09-29 05:20 UTC, ahmadkhandev commented on lib/all_utils.dart
> -
add these new lines back

2021-09-29 05:20 UTC, ahmadkhandev commented on lib/screens/game_kind/components/selection_card.dart
> +                const VerticalSpacing(of: 22),
use rounded off figures. use 20. remove the parameter

2021-09-29 05:20 UTC, ahmadkhandev commented on lib/screens/game_kind/game_kind_screen.dart
> +                )),
extract this widget out and name it OnboardingHeaderText and take a string in parameters

2021-09-29 05:20 UTC, ahmadkhandev commented on lib/screens/game_kind/game_kind_screen.dart
> +            ),
extract this widget out and take list as a parameter

2021-09-29 05:22 UTC, Tayyab-98 commented on lib/screens/game_kind/components/selection_card.dart
> +  final String image;
done

2021-09-29 05:22 UTC, Tayyab-98 commented on lib/all_utils.dart
> -
done

2021-09-29 05:23 UTC, Tayyab-98 commented on lib/screens/game_kind/components/selection_card.dart
> +                const VerticalSpacing(of: 22),
done

2021-09-29 05:26 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +                )),
done

2021-09-29 05:47 UTC, mhanzla80 approved these changes

2021-09-29 06:56 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
> +            ),
done

2021-09-29 07:01 UTC, mhanzla80 commented on lib/screens/game_kind/components/selection_card.dart
> +                child: Checkbox(
reactor checkbox widget.

2021-09-29 07:01 UTC, mhanzla80 commented on lib/screens/game_kind/components/selection_card_gridview.dart
> +import 'package:flutter/material.dart';
remove this.

2021-09-29 07:02 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
>  import 'package:flutter/material.dart';
remove it

2021-09-29 07:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/header_text.dart
> +import 'package:flutter/material.dart';
done

2021-09-29 07:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/image_with_text.dart
> +class ImageWithText extends StatelessWidget {
done

2021-09-29 07:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/selection_card.dart
>  import 'package:flutter/material.dart';
done

2021-09-29 07:06 UTC, Tayyab-98 commented on lib/screens/game_kind/components/selection_card.dart
> +                child: Checkbox(
done

2021-09-29 07:07 UTC, Tayyab-98 commented on lib/screens/game_kind/components/selection_card_gridview.dart
> +import 'package:flutter/material.dart';
done

2021-09-29 07:07 UTC, Tayyab-98 commented on lib/screens/game_kind/game_kind_screen.dart
>  import 'package:flutter/material.dart';
done

2021-09-29 07:07 UTC, mhanzla80 submitted a review, later dismissed

2021-09-29 07:15 UTC, Tayyab-98 commented
<img src="https://user-images.githubusercontent.com/89379559/135220727-b39d6da1-c106-4cfa-90a9-5f9905f99878.png" width="200"/>

2021-09-29 08:18 UTC, nooralibutt requested changes

2021-09-29 08:18 UTC, nooralibutt commented on lib/all_utils.dart
> +export 'package:flutter/material.dart';
remove duplications here

2021-09-29 08:18 UTC, nooralibutt commented on lib/screens/game_kind/components/header_text.dart
> +class OnboardingHeaderText extends StatelessWidget {
change it to header text and take subtitle here as well

2021-09-29 08:37 UTC, nooralibutt requested changes

2021-09-29 08:37 UTC, nooralibutt commented on lib/screens/game_kind/components/image_with_text.dart
> +          width: 64.w,
keep both same. either 64.w or 64.h

2021-09-29 08:37 UTC, nooralibutt commented on lib/screens/game_kind/components/selection_card_gridview.dart
> +          itemBuilder: (BuildContext ctx, index) {
use fat arrow here

2021-09-29 10:52 UTC, mhanzla80 requested changes

2021-09-29 10:52 UTC, mhanzla80 commented on lib/screens/game_kind/game_kind_screen.dart
> +            HeaderText(
const ??

2021-09-29 11:43 UTC, nooralibutt approved these changes

2021-09-29 11:52 UTC, merged