Tayyab 98/practice type screen UI #17
nooralibutt/playon pull request #22
Opened 2021-09-27 10:23 UTC by Tayyab-98

2021-09-27 10:46 UTC, mhanzla80 commented on lib/screens/practise_type_screen-ui/practise_type_screen_ui.dart
> +class PracticeTypeList extends StatefulWidget {
refactor it

2021-09-27 10:46 UTC, mhanzla80 commented on lib/all_utils.dart
> -
revert it.

2021-09-27 11:10 UTC, mhanzla80 commented on lib/screens/practise_type_screen-ui/components/practice_type_list.dart
> +              setState(() {
write it in one line

2021-09-27 11:10 UTC, mhanzla80 commented on lib/screens/practise_type_screen-ui/components/practice_type_list.dart
> +          of: 10.h,
write it in one line.

2021-09-28 05:11 UTC, Haiderali29 submitted a review, later dismissed

2021-09-28 06:39 UTC, mhanzla80 approved these changes

2021-09-28 07:28 UTC, mhanzla80 requested changes

2021-09-28 07:28 UTC, mhanzla80 commented on lib/screens/practise_type/components/checkbox_list.dart
> +                title: Text(widget.title,
why are you not using .toText Widget instead of Text() widget.

2021-09-28 07:28 UTC, mhanzla80 commented on lib/screens/practise_type/components/checkbox_list.dart
> +                    style: TextStyle(
try to do const textStyle.

2021-09-28 07:43 UTC, mhanzla80 submitted a review, later dismissed

2021-09-28 08:27 UTC, nooralibutt requested changes

2021-09-28 08:46 UTC, mhanzla80 approved these changes

2021-09-28 09:06 UTC, mhanzla80 approved these changes

2021-09-28 09:49 UTC, Haiderali29 commented on lib/screens/practise_type/components/checkbox_tile.dart
> +  const CheckBoxTile({required this.title, Key? key}) : super(key: key);
Rename CheckBoxTile to CheckboxTile

2021-09-28 09:51 UTC, Haiderali29 commented on lib/screens/practise_type/components/checkbox_tile.dart
> +                    style: const TextStyle(
assign fontsize and color as a widget parameter instead of using style

2021-09-28 09:59 UTC, mhanzla80 submitted a review, later dismissed

2021-09-28 10:01 UTC, Haiderali29 commented on lib/screens/practise_type/practise_type_screen.dart
> +  const PracticeType({Key? key}) : super(key: key);
specify routeName as
static const routeName = '/practise_type_screen';

2021-09-28 10:06 UTC, Haiderali29 commented on lib/main.dart
> +        initialRoute: PracticeTypeScreen.routeName,
Revert it back to SplashScreen.routeName

2021-09-28 10:11 UTC, mhanzla80 requested changes

2021-09-28 10:11 UTC, mhanzla80 commented on lib/screens/practise_type/components/checkbox_tile.dart
> +                onChanged: (bool? value) => setState(() {
make it in one line.

2021-09-28 10:11 UTC, mhanzla80 commented on lib/screens/practise_type/practise_type_screen.dart
> +          padding: EdgeInsets.symmetric(horizontal: 20),
const plz

2021-09-28 10:11 UTC, mhanzla80 commented on lib/screens/practise_type/practise_type_screen.dart
> +              VerticalSpacing(of: 235),
const plz

2021-09-28 10:55 UTC, Tayyab-98 commented
<img src="https://user-images.githubusercontent.com/89379559/135074155-019f7cbf-0410-4850-ade8-15977b362106.png" width="200"/>

2021-09-29 07:33 UTC, mhanzla80 submitted a review, later dismissed

2021-09-29 12:02 UTC, mhanzla80 requested changes

2021-09-29 12:02 UTC, mhanzla80 commented on lib/screens/practise_type/components/checkbox_tile.dart
> +  bool? _value = false;
remove nullable ...

2021-09-29 12:02 UTC, mhanzla80 commented on lib/screens/practise_type/practise_type_screen.dart
> +                padding: EdgeInsets.symmetric(horizontal: kDefaultPadding),
const

2021-09-29 15:19 UTC, ahmadkhandev commented on lib/screens/practise_type/components/checkbox_tile.dart
> +  bool? _value = false;
no, it is needed to be nullable

2021-09-30 07:40 UTC, nooralibutt submitted a review, later dismissed

2021-09-30 07:41 UTC, mhanzla80 submitted a review, later dismissed

2021-09-30 07:44 UTC, nooralibutt approved these changes

2021-09-30 07:47 UTC, mhanzla80 approved these changes

2021-09-30 07:54 UTC, mhanzla80 approved these changes

2021-09-30 07:55 UTC, merged